# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Boutique Lella Aicha
email: boutiquelellaaicha@gmail.com
author: Boutique Lella Aicha
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 Boutique Lella Aicha. All Rights Reserved.'
credits: 'Credits: theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - prefix: fa fa-
    title: facebook
    url: https://www.facebook.com/
    suffix: fa-fw
  - prefix: fa fa-
    title: instagram
    url: https://www.instagram.com/
    suffix: fa-fw
  - prefix: fa fa-
    title: pinterest
    url: https://www.pinterest.com/
    suffix: fa-fw
  # - prefix: fab fa-
  #   title: etsy
  #   url: https://www.etsy.com/de/shop/BoutiqueLellaAicha
  #   suffix:
